server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
    url: ${CLEARDB_DATABASE_URL:jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true}
  jpa:
    hibernate:
      ddl-auto: update